name: Build Website to APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Web-to-APK
        uses: GearS3/web-to-apk-action@v1
        with:
          url: 'https://masmu.sch.id/'
          app_name: 'MASMU Mobile'
          package_name: 'id.sch.masmu.app'

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MASMU-APK
          path: '**/*.apk'
